### ISSUE TITLE
Inconsistent Formatting/Alignment of Results

### ISSUE THREAD

**Issue by museHD** [museHD/MultiDefine#15]
The current formatting of words is quite inconsistent, adding spaces for some results, but not for others,
I believe this is because different sources have different formatting. This results in unaligned output, as shown:

![image](https://user-images.githubusercontent.com/57558058/137137351-34a216ac-aca2-40f6-8244-b8380ec78b3c.png)

This should be easy to fix by stripping the data collected, removing spaces and/or newlines and making sure that all of them are aligned.

**Comment by Michael36500** [comment]
maybe you can mark this issue as close...
